# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

guestuser1 = User.create(username: "GuestUser", password: "GuestUser")
guestuser2 = User.create(username: "superBoards", password: "superBoards")
# # AppAcademy Boards
# aa_board = Board.create(title: "App Academy", author_id: 3)
# # aa_board.shares.create(user_id: 1)
# # aa_board.shares.create(user_id: 3)
# tas = aa_board.lists.create(title: "TAs", ord: 0, archived: false)
# Card.create(title: "Leen", list_id: tas.id, ord: 0, archived: false, author_id: 3)
# Card.create(title: "Tommy", list_id: tas.id, ord: 1, archived: false, author_id: 3, description: "Good morning everybody!")
# Card.create(title: "Carl", list_id: tas.id, ord: 2, archived: false, author_id: 3)
# Card.create(title: "Lily", list_id: tas.id, ord: 3, archived: false, author_id: 3, description: "Good morning pod!")
# Card.create(title: "Fred", list_id: tas.id, ord: 4, archived: false, author_id: 3)
# cats = aa_board.lists.create(title: "Cats", ord: 1, archived: false)
# Card.create(title: "Gizmo", list_id: cats.id, ord: 0, archived: false, author_id: 3)
# Card.create(title: "Sennacy", list_id: cats.id, ord: 1, archived: false, author_id: 3)
# Card.create(title: "Breakfast", list_id: cats.id, ord: 2, archived: false, author_id: 3)
# languages = aa_board.lists.create(title: "Languages", ord: 2, archived: false)
# Card.create(title: "CSS", list_id: languages.id, ord: 0, archived: false, author_id: 3)
# Card.create(title: "Ruby", list_id: languages.id, ord: 1, archived: false, author_id: 3)
# Card.create(title: "Javascript", list_id: languages.id, ord: 2, archived: false, author_id: 3)
# Card.create(title: "SQL", list_id: languages.id, ord: 3, archived: false, author_id: 3)
# Card.create(title: "HTML", list_id: languages.id, ord: 4, archived: false, author_id: 3)
# libraries = aa_board.lists.create(title: "Frameworks / Libraries", ord: 3, archived: false)
# Card.create(title: "Flux", list_id: libraries.id, ord: 0, archived: false, author_id: 3)
# Card.create(title: "Rails", list_id: libraries.id, ord: 1, archived: false, author_id: 3)
# Card.create(title: "JQuery", list_id: libraries.id, ord: 2, archived: false, author_id: 3)
# Card.create(title: "React", list_id: libraries.id, ord: 3, archived: false, author_id: 3)
# pods = aa_board.lists.create(title: "Pods", ord: 4, archived: false)
# Card.create(title: "East Village", list_id: pods.id, ord: 0, archived: false, author_id: 3)
# Card.create(title: "Harlem", list_id: pods.id, ord: 1, archived: false, author_id: 3)
# Card.create(title: "Brooklyn", list_id: pods.id, ord: 2, archived: false, author_id: 3)
# Card.create(title: "Soho", list_id: pods.id, ord: 3, archived: false, author_id: 3)
# jonathan = aa_board.lists.create(title: "Jonathan", ord: 5, archived: false)
# ycdi = jonathan.cards.create(title: "You can do it!", ord: 0, archived: false, author_id: 3)
# AppTour board and lists
demo_board = Board.create(title: "Welcome to superBoards. Click this board!", author_id: guestuser1.id)
demo_board.shares.create(user_id: 2)
demo_board.shares.create(user_id: 3)
demo_list_1 = demo_board.lists.create(title: "Cards", ord: 0)
demo_list_2 = demo_board.lists.create(title: "Lists", ord: 1)
demo_list_3 = demo_board.lists.create(title: "Boards", ord: 2)
demo_list_1.cards.create(title: "Welcome to superBoards!", ord: 0, author_id: guestuser1.id)
demo_list_1.cards.create(title: "This is a card.", ord: 1, author_id: guestuser1.id)
demo_card = demo_list_1.cards.create(title: "Click this card to see more details.", ord: 2, author_id: guestuser1.id, description: "Cards can have a brief description.")
demo_list_2.cards.create(title: "You can have many lists within a board.", ord: 0, author_id: guestuser1.id)
demo_list_2.cards.create(title: "And many cards within those lists.", ord: 1, author_id: guestuser1.id)
demo_list_2.cards.create(title: "You can also reorder lists by dragging them.", ord: 2, author_id: guestuser1.id)
demo_list_2.cards.create(title: "Guess what? You can drag and drop cards too.", ord: 3, author_id: guestuser1.id)
demo_list_2.cards.create(title: "Try it. (We insist)", ord: 4, author_id: guestuser1.id)
demo_list_3.cards.create(title: "Boards hold all your content in superBoards.", ord: 0, author_id: guestuser1.id)
demo_list_3.cards.create(title: "Boards can be shared with other users to collaborate!", ord: 1, author_id: guestuser1.id)
demo_list_3.cards.create(title: "Sharing options are available in the board menu.", ord: 2, author_id: guestuser1.id)
demo_list_3.cards.create(title: "Once you're finished with a board, you can archive it.", ord: 3, author_id: guestuser1.id)
demo_list_3.cards.create(title: "Please note, only the owner of a board can share or archive it.", ord: 4, author_id: guestuser1.id)
demo_card.comments.create(body: "Cards can also have comments.", author_id: guestuser2.id)
demo_card.comments.create(body: "All users that have access to a board can leave comments.", author_id: guestuser2.id)
# A sample project
